# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PROTOCOL)                       += protocol/
obj-$(CONFIG_XM_SUB_PMIC)                    += subpmic_base/
obj-$(CONFIG_SUBPMIC_SC6601A_DRIVER)         += subpmic_sc6601a/
obj-$(CONFIG_SUBPMIC_SY6976_DRIVER)          += subpmic_sy6976/
obj-$(CONFIG_SUBPMIC_NU6601_DRIVER)          += subpmic_nu6601/
obj-$(CONFIG_CHARGEPUMP)                     += chargepump/
