# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SC8551_CHARGER)     +=   sc8551_charger.o
obj-$(CONFIG_SC853X_CHARGER)     +=   sc853x_charger.o
obj-$(CONFIG_BQ25960_CHARGER)    +=   bq25960_charger.o
obj-$(CONFIG_BQ25960_CHARGER)    +=   bq25960h_charger.o
