obj-$(CONFIG_LC_ADAPTER_CLASS)	+= lc_adapter_class.o

obj-$(CONFIG_LC_CHARGER_CLASS)	+= lc_charger_class.o

obj-$(CONFIG_LC_CP_CLASS)		+= lc_cp_class.o

obj-$(CONFIG_LC_LED_CLASS)		+= lc_led_class.o

obj-$(CONFIG_PD_BATTERY_SECRET)		+= xm_adapter_class.o

obj-$(CONFIG_BQ_FUELGAUGE)		+= lc_fg_class.o
